name: The Wellness Retreats
favicon: null
layout_spectrum: 0.2212
typography_spectrum: 0.9672766432631761
title: The Wellness Retreats
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#abff45'
    - '#4edbff'
    - '#666666'
    - '#b2b2b2'
  brandStrength: 0.012113653821870685
  lightness: 0.3125
  saturation: 0.18312972178682685
  rhythmicContrast: 0.2701794686727226
purpose: []
